### ISSUE TITLE
Separate download for options and weights

### ISSUE THREAD

**Issue by stefan-it** [t-systems-on-site-services-gmbh/german-elmo-model#2]
Hi @PhilipMay,

thanks for releasing this German ELMo model :+1: 

I've one question: would it be possible that you provide the `options.json` and `weights.hdf5` as separate downloads 🤔

I would really like to include the model in [Flair](https://github.com/zalandoresearch/flair) and this could be done directly whenever there's a direct url for options and the weights file.

E.g. for my recently trained model on Basque it would be possible with:

```python
embeddings = ELMoEmbeddings(options_file="https://schweter.eu/cloud/eu-elmo/options.json", 
                            weight_file="https://schweter.eu/cloud/eu-elmo/weights.hdf5")
```

As you can see, it is only necessary to pass an url to the `options.json` and `weights.hdf5` file.

Would be really awesome if you can provide these two files :heart: 

Thanks in advance,

Stefan

**Comment by PhilipMay** [comment]
Hey @stefan-it - here are the two files:

https://github.com/t-systems-on-site-services-gmbh/german-elmo-model/releases/download/files_1/options.json

https://github.com/t-systems-on-site-services-gmbh/german-elmo-model/releases/download/files_1/weights.hdf5

For checksums see here:
https://github.com/t-systems-on-site-services-gmbh/german-elmo-model/blob/master/README.md#download-options-and-weights-files-only

**Comment by PhilipMay** [comment]
@stefan-it can you please tell me if I can close the issue?

PS: Maybe you should try to fine tune this model with your language data. That might improve performance.

**Comment by stefan-it** [comment]
@PhilipMay Thanks for adding this! When I download options and weights locally it is perfectly working! I'll do some more experiments on CoNLL-2003 in a few days :)
