### ISSUE TITLE
Cannot unzip file

### ISSUE THREAD

**Issue by ghost** [t-systems-on-site-services-gmbh/german-elmo-model#3]
Hey there,

unfortunately I wasn't able to unzip the files provided in the readme.md file. Therefore I downloaded the options.json and the weights.hdf5 files, but I also need the vocabulary file. Could you provide that for download as well please?

**Comment by PhilipMay** [comment]
Please check the Unpack section: https://github.com/t-systems-on-site-services-gmbh/german-elmo-model#unpack

**Comment by ghost** [comment]
Do I just need to download one of the .part-* files or do I need to download all of them and merge them? Unzipping the file .part-03 didn't work with the provided commands, so could you provide the vocab-train.txt separately?

**Comment by PhilipMay** [comment]
You have to download them all.

**Comment by ghost** [comment]
Yes, that worked! Thank you!

**Comment by PhilipMay** [comment]
Great! So I close the tocket. If you have more questions feel free to open up a new.
